version: "3.1"

services:
  db:
    image: postgres:15
    restart: always
    ports:
      - "25432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nextjsdash
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
